### ISSUE TITLE
现在还能使用吗？每次发指令都遇到WebSocket连接上的问题

### ISSUE THREAD

**Issue by AbigailWilliams1692** [LuckySJTU/nonebot-plugin-arxivRSS#1]
我在部署后试着向bot发出了命令 “/arxiv push cs.AI” 然后就遇到了如下的问题，是不是和go-cqhttp项目停止维护有关呀？

> 12-14 01:06:38 [WARNING] nonebot_plugin_gocqhttp | [#########] 监听反向WS Universal时出现错误: read tcp 127.0.0.1:54363->127.0.0.1:43992: use of closed network connection                                                                      
12-14 01:06:42 [WARNING] nonebot_plugin_gocqhttp | [########] 向反向WS Universal服务器推送 Event 时出现错误: write tcp 127.0.0.1:54363->127.0.0.1:43992: use of closed network connection                                                      
12-14 01:06:45 [INFO] nonebot_plugin_gocqhttp | [#########] 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:43992/onebot/v11/ws                                                                                                     

> File "C:\Users\Lenovo\OneDrive\repo\InfoFeedBot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 146, in _call_api                                                                                                           
raise NetworkError(f"WebSocket call api {api} timeout") from None                                                   nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api send_private_forward_msg timeout')

**Comment by LuckySJTU** [comment]
看起来像是配置ws的问题。你试试其他指令呢（比如echo）？
